### ISSUE TITLE
Any ETA on stable version supporting PHP 8?

### ISSUE THREAD

**Issue by racinmat** [contributte/redis#18]
Hi, the latest stable version is not compatible with PHP 8 according to composer.json, can we expect it released any time soon?
Thanks.

**Comment by dakorpar** [comment]
dev-master is currently ready.
I'm not sure will we release stable version before @fmasa prepares PR
https://github.com/contributte/redis/pull/16
https://github.com/contributte/redis/issues/14#issuecomment-748540409
This is also BC so not sure...
 @f3l1x maybe releasing this like it is and do this other stuff in next version?

**Comment by f3l1x** [comment]
Yep, good point. https://github.com/contributte/redis/releases/tag/v0.3.0
