### ISSUE TITLE
Redis journal

### ISSUE THREAD

**Issue by dada-amater** [contributte/redis#2]
Hi, thank you for your job. We would like to replace `Kdyby/redis` package by this one, but we use redis journal which is misding here. Do you have any plans to implement it? Thank you.

**Comment by f3l1x** [comment]
Hi. Well, we can copy-paste it from Kdyby or sosomemeone has to reimplement it.

**Comment by paveljanda** [comment]
Copy & paste from kdyby would make sense - it is pretty straightforward and testable code.

**Comment by dada-amater** [comment]
Do you have any idea, when it will be implemented? :-)

**Comment by f3l1x** [comment]
@dada-amater I am quite busy with Nette 3 upgrades for whole contributte packagist. Could you prepare PR?

**Comment by f3l1x** [comment]
Hi @dada-amater. I am pretty sure it's too late for you and you've implemented it your way. Could you please prepare a PR with your way? :-)

**Comment by bckp** [comment]
@f3l1x i belive this issue is resolved now :)

**Comment by f3l1x** [comment]
Solved. Thanks.
