### ISSUE TITLE
Config validation

### ISSUE THREAD

**Issue by repli2dev** [contributte/redis#23]
In `RedisExtension` the validation is expecting `string` specified in the config, however use `::getEnv()` is sometime needed especially when there is need to provide Redis configuration (host etc) from the ENV variables (`Nette\DI\Statement` will come in such cases).

This currently fails and needs to be bypassed in some hackish ways, could this library natively support it?

**Comment by repli2dev** [comment]
There is a relevant topic on Nette forum: https://forum.nette.org/cs/33414-vyhodnoceni-nette-di-statement-v-rozsireni#p210489

**Comment by f3l1x** [comment]
Hi. Thx. Can you prepare a change in PR?

**Comment by repli2dev** [comment]
@f3l1x Here it is !24

**Comment by f3l1x** [comment]
Solved.
