### ISSUE TITLE
Non-string value passed to processStoredValue

### ISSUE THREAD

**Issue by repli2dev** [contributte/redis#34]
Occasionally in production we see
```
Argument 2 passed to Contributte\Redis\Caching\RedisStorage::processStoredValue() must be of the type string, object given, called in /code/vendor/contributte/redis/src/Caching/RedisStorage.php on line 288
```

The value we see as attempted to be passed is `Object Predis\Response\Status` which is not specified in the Client PHPDoc ([similar cases were already fixed before](https://github.com/predis/predis/issues/709)) nor [Redis docs](https://redis.io/commands/get). However from some searches the Redis can return some status when under high load (see [this](https://github.com/redis/jedis/issues/397)).

Could there be a more safe treatment of the the value to prevent the above error?

**Comment by repli2dev** [comment]
I could prepare the MR, however I need guidance how the error handling should be done... throw an exception and let it on the client to handle? Retry? Return null content?

**Comment by f3l1x** [comment]
Well, I am not sure neither. Can you prepare some alpha-version?

**Comment by repli2dev** [comment]
@f3l1x would like to, but first the changes in linkdd predis/predis repo needs to be done basically :/

**Comment by adamdafcik** [comment]
I've encountered same issue. The problem seems to be only with method `RedisStorage::doMultiRead` because of strict comparison with false. I think it should enough to compare to falseable value as in method `RedisStorage::doRead`. What do you think?

**Comment by f3l1x** [comment]
Sure thing, prepare PR please and cover it by tests. I will merge it ASAP.
