### ISSUE TITLE
Passing down ENV variables to the configuration results in error

### ISSUE THREAD

**Issue by duchymor** [contributte/redis#36]
Passing down ENV variables to the configuration results in error:
_The item 'redis › connection › default › uri' expects to be string|list, object Nette\DI\DynamicParameter given._

contributte/redis: 0.4.1
Nette: 3.1
PHP: 7.4

**Comment by f3l1x** [comment]
Can you show me more? NEON etc.

**Comment by duchymor** [comment]
https://github.com/contributte/redis/tree/master/.docs#env-variables

**Comment by duchymor** [comment]
Seems the error is produced by this schema validation:
https://github.com/contributte/redis/blob/ff4bc25a638ec490c71d850214a9d233f1bb6262/src/DI/RedisExtension.php#L33

![image](https://user-images.githubusercontent.com/42995320/153630419-b48cad36-7d36-45f7-8513-5e34f17fe279.png)

**Comment by kickz** [comment]
> Seems the error is produced by this schema validation:
> 
> https://github.com/contributte/redis/blob/ff4bc25a638ec490c71d850214a9d233f1bb6262/src/DI/RedisExtension.php#L33
> 
> ![image](https://user-images.githubusercontent.com/42995320/153630419-b48cad36-7d36-45f7-8513-5e34f17fe279.png)

I also have the same problem.

**Comment by f3l1x** [comment]
Can you show me versions of contributte/* and nette/* libraries? There is a test for this case, I don't understand that.

How do you provide dynamic parameters? Can you show me?

https://github.com/contributte/redis/commit/0fc1881373cc6fd72de5f567fed003cf83ec5081#diff-d56437b860a29058e2b3a6e2a24a8e2cf18a4abd49a51c678eb17a0a90529cecR136-R161

**Comment by duchymor** [comment]
aah I finally got it... It happens if you simply follow docs. Because composer installs stable but readme is newer which is not obvious and one can't know that functionality is only available in 0.5.x-dev.

**Comment by f3l1x** [comment]
Solved https://github.com/contributte/redis/releases/tag/v0.5.0
