### ISSUE TITLE
backward support for nette 2.4

### ISSUE THREAD

**Issue by Barbarossa-42** [contributte/redis#6]
Hi @mabar, thanks for this extension! 

Can you please create release tag `0.1.1` from commit `f4815a0` (before nette 3.0 restrict)? We were using master (in locked composer) for long time, now we need to run composer update and there is conflict :) 

I tried 0.1 version in composer and there is issue with: `Reference to missing service 'redis.client'.`

**Comment by mabar** [comment]
Done
